# примеры API-запросов

###

# получение списка книг с именем автора
GET http://localhost:8000/api/v1/books/
Content-Type: application/json

###

# получение данных книги по id
GET http://localhost:8000/api/v1/books/3/
Content-Type: application/json

###

# создание книги
POST http://localhost:8000/api/v1/books/
Content-Type: application/json

{
  "name": "Судьба человека"
}

###

# обновление данных книги
PATCH http://localhost:8000/api/v1/books/3/
Content-Type: application/json

{
  "name": "Смерть Ахиллеса"
}

###

# удаление книги
DELETE http://localhost:8000/api/v1/books/3/
Content-Type: application/json
